<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	CosmoCommerce
 * @package 	CosmoCommerce_99Bill
 * @copyright	Copyright (c) 2009 CosmoCommerce,LLC. (http://www.cosmocommerce.com)
 * @contact :
 * T: +86-021-66346672
 * L: Shanghai,China
 * M:sales@cosmocommerce.com
 */
?>

<div class="form-divst">
		<img src="<?php echo $this->getSkinUrl('images/cosmo99bill/ljzf02.gif') ?>" />
<br/>
</div>
<fieldset class="form-divst">
	<?php $_code=$this->getMethodCode() ?>
	
	<ul id="payment_form_<?php echo $_code ?>" style="display:none">

	<div >
<img src="<?php echo $this->getSkinUrl('images/cosmo99bill/bank_boc.gif') ?>"> <img src="<?php echo $this->getSkinUrl('images/cosmo99bill/bank_ccb.gif') ?>"> <img src="<?php echo $this->getSkinUrl('images/cosmo99bill/bank_icbc.gif') ?>"> <img src="<?php echo $this->getSkinUrl('images/cosmo99bill/bank_cmb.gif') ?>"> <img src="<?php echo $this->getSkinUrl('images/cosmo99bill/bank_cmbc.gif') ?>"> <br />
<img src="<?php echo $this->getSkinUrl('images/cosmo99bill/bank_spdb.gif') ?>"> <img src="<?php echo $this->getSkinUrl('images/cosmo99bill/bank_gdb.gif') ?>"> <img src="<?php echo $this->getSkinUrl('images/cosmo99bill/bank_hxb.gif') ?>"> <img src="<?php echo $this->getSkinUrl('images/cosmo99bill/bank_bosh.gif') ?>"> <img src="<?php echo $this->getSkinUrl('images/cosmo99bill/bank_cib.gif') ?>"> <br />

	</div><br />
	</ul>
	<div style="clear:both;">
		<?php echo $this->__('You will be redirected to 99bill website when you place an order.') ?>
	</div>
</fieldset>